name: Build Android .so Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: actions/setup-android@v1
      with:
        ndk-version: '23.1.7779620'  # Specify the NDK version

    - name: Set up CMake
      uses: actions/setup-cmake@v2

    - name: Build Android .so library with CMake
      run: |
        mkdir build
        cd build
        cmake -DANDROID_NDK=${{env.ANDROID_NDK_HOME}} -DCMAKE_TOOLCHAIN_FILE=${{env.ANDROID_NDK_HOME}}/build/cmake/android.toolchain.cmake ..
        cmake --build .

    - name: Archive the output .so library
      run: tar czf my_android_lib.tar.gz ./build/libmyandroidlib.so
      # This will archive your .so file for later use