name: Build Android .so Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Android NDK
    - name: Set up Android NDK
      run: |
        # Download and extract the Android NDK
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux-x86_64.zip
        unzip android-ndk-r23b-linux-x86_64.zip
        mv android-ndk-r23b $HOME/android-ndk
        echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV

    # Install CMake
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    # Build Android .so library with CMake
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake -DANDROID_NDK=$HOME/android-ndk -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk/build/cmake/android.toolchain.cmake ..
        cmake --build .

    # Archive the output .so library
    - name: Archive the output .so library
      run: |
        tar czf my_android_lib.tar.gz ./build/libmyandroidlib.so